### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by WillEccles** [RUSshy/game#1]
Since clearly you couldn't make this pan out in C++ quite how you wanted it, maybe you should switch to Rust. I hear it's pretty good at making things.

**Comment by diamondburned** [comment]
Downvoted. As V is the future and can compile DOOM in not even a second, this should be rewritten in V and maintained in V.

**Comment by ym1234** [comment]
I agree, Rust has a pretty clear syntax. It is actually very similar to the one you used here https://github.com/dotnet/csharplang/issues/2615 , but sadly the rust team refused to rewrite it in. https://github.com/rust-lang/rust/issues/62060 :(

**Comment by WillEccles** [comment]
@diamondburned Honestly, I see no reason to do that. Jai is just better than both of those, although Zig would be a decent alternative.

**Comment by diamondburned** [comment]
![image](https://user-images.githubusercontent.com/8463786/65191578-448b3980-da29-11e9-8a36-4e91f21e8fb6.png)

**Comment by fr3fou** [comment]
+1 for V

**Comment by RUSshy** [comment]
V is indead the future, i'll rewrite it in Verona, rust is a game after all https://store.steampowered.com/app/252490/Rust/

time to find new job crapzilla people, i heard scala is hiring lol
