### ISSUE TITLE
Repository doesn't follow your preferred coding style

### ISSUE THREAD

**Issue by ym1234** [RUSshy/game#2]
According to [this](https://github.com/golang/go/issues/18978) your brain refuses to accept this style
```cpp
    struct position {
        float x;
        float y;
    };

    struct velocity {
        float dx;
        float dy;
    };
```
 maybe this should be fixed?

**Comment by RUSshy** [comment]
i am not working on this project anymore

but since u like to help me, please help me finish this task:

https://github.com/rust-lang/rust-clippy/pull/4974
